export const CREATE_LIST_START = "list/CREATE_LIST_START";
export const CREATE_LIST_COMPLETED = "list/CREATE_LIST_COMPLETED";
export const EDIT_LIST_START = "list/EDIT_LIST_START";
export const EDIT_LIST_COMPLETED = "list/EDIT_LIST_COMPLETED";
export const DELETE_LIST_START = "list/DELETE_LIST_START";
export const DELETE_LIST_COMPLETED = "list/DELETE_LIST_COMPLETED";
export const CREATE_CARD_START = "list/CREATE_CARD_START";
export const CREATE_CARD_COMPLETED = "list/CREATE_CARD_COMPLETED";



