export const CREATE_LIST_COMPLETED = "list/CREATE_LIST_COMPLETED";
export const EDIT_LIST_COMPLETED = "list/EDIT_LIST_COMPLETED";
export const DELETE_LIST_COMPLETED = "list/DELETE_LIST_COMPLETED";
export const CREATE_CARD_COMPLETED = "list/CREATE_CARD_COMPLETED";
export const DELETE_CARD_COMPLETED = "list/DELETE_CARD_COMPLETED";
export const EDIT_CARD_COMPLETED = "list/EDIT_CARD_COMPLETED";
export const DROP_CARD_COMPLETED = "list/DROP_CARD_COMPLETED";




